# -*- coding: utf-8 -*-
"""downcast_polars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEPIE4hYuyZgCBQhAFbDLKGYIG3CWsC6
"""

import sys
import polars as pl
import polars.selectors as cs
import pyarrow as pa
import lance
import s3fs
import farmhash
from tqdm.auto import tqdm

#!{sys.executable} -m pip install -q s3fs pyarrow polars pyfarmhash lance

sys.path.insert(0, '/home/ubuntu/vastaiFinal')


BUCKET = 'solana-flash-chunks-668889064578-ca-central-1-an'
PREFIX = 'project_chunks'
OUT    = '/home/ubuntu/vastaiFinal/processed.lance'

print(f'Source : s3://{BUCKET}/{PREFIX}/*.feather')
print(f'Output : {OUT}')

# ── List feather files on S3, read with Polars, cast numerics → float32 ───────
s3 = s3fs.S3FileSystem()
paths = sorted(s3.glob(f'{BUCKET}/{PREFIX}/*.feather'))
print(f'Files found: {len(paths)}')

frames = []
for path in tqdm(paths):
    with s3.open(path, 'rb') as f:
        chunk = pl.read_ipc(f)
    chunk = chunk.with_columns(cs.numeric().cast(pl.Float32))
    # ── Deterministic wallet sample (mirrors BigQuery FARM_FINGERPRINT % 300, 3) ──────
    chunk = chunk.filter(
        pl.col('wallet').map_elements(
            lambda w: abs(farmhash.fingerprint64(w)) % 300 == 0,
            return_dtype=pl.Boolean,
        )
    )
    frames.append(chunk)

df = pl.concat(frames)
del frames

print(f'Rows    : {df.shape[0]:,}')
print(f'Wallets : {df["wallet"].n_unique():,}')
print(f'Columns : {df.columns}')

# ── Engineer features (Polars equivalent of preprocess.engineer_features) ─────
exprs = []

# Fill nulls from BigQuery left/outer joins
for col in ('instigator_net_token_profit', 'instigator_fiat_delta', 'instigator_sol_delta'):
    if col in df.columns:
        exprs.append(pl.col(col).fill_null(0.0))

# Composability ratios
if {'unique_program_count', 'unique_nonsigner_account_count'}.issubset(df.columns):
    exprs.append(
        pl.when(pl.col('unique_nonsigner_account_count') == 0)
          .then(0.0)
          .otherwise(pl.col('unique_program_count') / pl.col('unique_nonsigner_account_count'))
          .cast(pl.Float32)
          .alias('hop_density')
    )

if {'max_cpi_depth', 'unique_program_count'}.issubset(df.columns):
    exprs.append(
        pl.when(pl.col('unique_program_count') == 0)
          .then(0.0)
          .otherwise(pl.col('max_cpi_depth') / pl.col('unique_program_count'))
          .cast(pl.Float32)
          .alias('avg_depth_per_protocol')
    )

# Novel contract count
if {'unique_program_count', 'dex_hop_count', 'debt_hop_count'}.issubset(df.columns):
    exprs.append(
        (pl.col('unique_program_count') - pl.col('dex_hop_count') - pl.col('debt_hop_count'))
          .clip(lower_bound=0)
          .cast(pl.Float32)
          .alias('unknown_program_count')
    )

# Profit flags
for col, alias in [
    ('instigator_fiat_delta',        'has_fiat_profit'),
    ('instigator_net_token_profit',  'has_token_profit'),
    ('instigator_sol_delta',         'has_sol_profit'),
]:
    if col in df.columns:
        exprs.append((pl.col(col) > 0).cast(pl.Int8).alias(alias))

df = df.with_columns(exprs)

print(f'Shape  : {df.shape}')
print(f'Columns: {df.columns}')

cache_path = 'engineered_features_cache.parquet'
# Save the DataFrame to disk
df.write_parquet(cache_path)

print(f'Successfully cached DataFrame to {cache_path}')
print(f'File size: {__import__("os").path.getsize(cache_path) / (1024*1024):.2f} MB')

cache_path = 'engineered_features_cache.parquet'

pl.read_parquet(cache_path)

# ── Null counts ────────────────────────────────────────────────────────────────
null_df = (
    df.null_count()
      .unpivot(variable_name='column', value_name='null_count')
      .with_columns(
          (pl.col('null_count') / df.shape[0] * 100).round(3).alias('null_pct')
      )
      .sort('null_count', descending=True)
)
print(null_df)

# ── Write Lance ────────────────────────────────────────────────────────────────
table = df.to_arrow()
lance.write_dataset(table, OUT, mode='overwrite')
del table

ds = lance.dataset(OUT)
print(f'Rows   : {ds.count_rows():,}')
print(f'Schema :\n{ds.schema}')